services:
  db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: bonjour
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuser
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: